monBlog/routes/web.php
<?php

use App\Http\Controllers\BilletsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('billets',BilletsController::class);

monBlog/app/Models/Billet.php
<?php

namespace App\Models;

use App\Models\Commentaire;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Billet extends Model
{
    use HasFactory;

    public function Commentaire() {
        return $this->hasMany(Commentaire::class);
    }
}

monBlog/app/Models/Commentaire.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Commentaire extends Model
{
    use HasFactory;

    public function Billet() {
        return $this->belongsTo(Billet::class);
    }

}

monBlog/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

monBlog/app/Http/Controllers/BilletsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorebilletsRequest;
use App\Http\Requests\UpdatebilletsRequest;
use App\Models\Billet;

class BilletsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $billets = Billet::all();
        return view('billets',compact('billets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorebilletsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorebilletsRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Billet  $billet
     * @return \Illuminate\Http\Response
     */
    public function show(Billet $billet)
    {
        $commentaires = $billet->commentaire;
        return view('commentaires',compact('billet','commentaires'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Billet  $billets
     * @return \Illuminate\Http\Response
     */
    public function edit(Billet $billets)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatebilletsRequest  $request
     * @param  \App\Models\Billet  $billets
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatebilletsRequest $request, Billet $billet)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Billet  $billets
     * @return \Illuminate\Http\Response
     */
    public function destroy(Billet $billet)
    {
        //
    }
}

monBlog/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

monBlog/resources/views/billets.blade.php
@extends('layouts.layout')

@section('titre')
    Tous les billets du blog
@endsection

@section('titrePage')
    Tous les billets :
@endsection

@section('contenu')
    @foreach($billets as $billet)
    <h1 id="titreBillet"><a href="{{ route('billets.show', $billet->id)}}">{{ $billet->BIL_Titre }}</a></h1>
    <p>{{ $billet->BIL_Date }}<br>
    {{ $billet->BIL_Contenu }}<br></p>
    @endforeach
@endsection

monBlog/resources/views/commentaires.blade.php
@extends('layouts.layout')

@section('titre')
    Commentaires du billet
@endsection

@section('titrePage')
    Commentaires
@endsection

@section('contenu')
    <h1 id="titreBillet">{{ $billet->BIL_Titre }}</h1>
    <p>{{ $billet->BIL_Date }}</p>
    <p>{{ $billet->BIL_Contenu }}</p>
    <hr>
    <p id="titreReponses">Réponses à {{ $billet->BIL_Titre }}</p>
    @foreach($commentaires as $com)
    <p>{{ $com->COM_Auteur }} dit :<br>
    {{ $com->COM_Contenu }}<br></p>
    @endforeach
@endsection

monBlog/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="css/monBlog.css"/>
        <title>@yield('titre')</title>
    </head>
    <body>
        <div id="global">
            <header id="titreBlog"><h1>@yield('titrePage')</h1></header>
            <div id="contenu">@yield('contenu')</div>
            <footer id="piedBlog">Monblog - copyright 3A Info - 2022</footer>
        </div>
    </body>
</html>